# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SD' do
  # Comment the next line if you don't want to use dynamic frameworks

pod 'YYWebImage'
pod 'YYImage/WebP'

  use_frameworks!

  # Pods for SD

end
